TABLE_SCHEMAS = {
    "dim_meta_accounts": {
        "id": "TEXT PRIMARY KEY",
        "account_name": "TEXT",
        "account_status": "INTEGER",
        "currency": "TEXT",
        "timezone_id": "INTEGER",
        "amount_spent": "NUMERIC",
        "spend_cap": "NUMERIC",
        "balance": "NUMERIC",
        "business_name": "TEXT",
        "disable_reason": "INTEGER",
        "funding_source_display": "TEXT",
        "funding_source_id": "TEXT",
        "funding_source_type": "TEXT",
        "created_time": "TIMESTAMPTZ",
    },
    "dim_meta_creatives": {
        "creative_id": "TEXT PRIMARY KEY",
        "account_id": "TEXT",
        "creative_name": "TEXT",
        "status": "TEXT",
    "object_story_id": "TEXT",
    "object_type": "TEXT",
    "object_story_spec": "JSONB",
    "asset_feed_spec": "JSONB",
    "template_url": "TEXT",
    "template_url_spec": "JSONB",
    "degrees_of_freedom_spec": "JSONB",
    "dynamic_ad_voice": "TEXT",
    "product_set_id": "TEXT",
    "url_tags": "TEXT",
    "link_url": "TEXT",
    "instagram_permalink_url": "TEXT",
    "image_hash": "TEXT",
    "image_url": "TEXT",
    "thumbnail_url": "TEXT",
        "video_id": "TEXT",
        "body": "TEXT",
        "title": "TEXT",
        "call_to_action_type": "TEXT",
        "preview_url": "TEXT",
    },
    "dim_meta_ads": {
        "ad_id": "TEXT PRIMARY KEY",
        "account_id": "TEXT",
        "ad_name": "TEXT",
        "adset_id": "TEXT",
        "campaign_id": "TEXT",
        "configured_status": "TEXT",
        "effective_status": "TEXT",
        "created_time": "TIMESTAMPTZ",
        "updated_time": "TIMESTAMPTZ",
        "preview_mobile_feed_basic": "TEXT",
        "preview_mobile_feed_basic_html": "TEXT",
        "preview_instagram_story": "TEXT",
        "preview_instagram_story_html": "TEXT",
        "preview_instagram_reels": "TEXT",
        "preview_instagram_reels_html": "TEXT",
    },
    "dim_meta_campaigns": {
        "campaign_id": "TEXT PRIMARY KEY",
        "campaign_name": "TEXT",
        "account_id": "TEXT",
        "created_time": "TIMESTAMPTZ",
        "start_time": "TIMESTAMPTZ",
        "stop_time": "TIMESTAMPTZ",
        "objective": "TEXT",
        "status": "TEXT",
        "effective_status": "TEXT",
        "buying_type": "TEXT",
        "daily_budget": "NUMERIC",
        "lifetime_budget": "NUMERIC",
        "budget_remaining": "NUMERIC",
    },
    "dim_meta_adsets": {
        "adset_id": "TEXT PRIMARY KEY",
        "adset_name": "TEXT",
        "account_id": "TEXT",
        "campaign_id": "TEXT",
        "created_time": "TIMESTAMPTZ",
        "start_time": "TIMESTAMPTZ",
        "end_time": "TIMESTAMPTZ",
        "status": "TEXT",
        "effective_status": "TEXT",
        "billing_event": "TEXT",
        "daily_budget": "NUMERIC",
        "lifetime_budget": "NUMERIC",
        "bid_amount": "NUMERIC",
        "optimization_goal": "TEXT",
        "targeting": "JSONB",
    },
    "dim_meta_ads_settings": {
        "ad_id": "TEXT PRIMARY KEY",
        "ad_name": "TEXT",
        "account_id": "TEXT",
        "adset_id": "TEXT",
        "campaign_id": "TEXT",
        "created_time": "TIMESTAMPTZ",
        "updated_time": "TIMESTAMPTZ",
        "status": "TEXT",
        "effective_status": "TEXT",
        "configured_status": "TEXT",
        "ad_review_feedback": "JSONB",
        "issues_info": "JSONB",
        "tracking_specs": "JSONB",
        "delivery_info": "JSONB",
        "creative_id": "TEXT",
        "creative_name": "TEXT",
    },
    "fact_meta_delivery_ad": {
        "ad_id": "TEXT",
        "date_start": "DATE",
        "date_stop": "DATE",
        "account_id": "TEXT",
        "account_name": "TEXT",
        "campaign_id": "TEXT",
        "campaign_name": "TEXT",
        "adset_id": "TEXT",
        "adset_name": "TEXT",
        "ad_name": "TEXT",
        "objective": "TEXT",
        "optimization_goal": "TEXT",
        "spend": "NUMERIC",
        "social_spend": "NUMERIC",
        "reach": "NUMERIC",
        "impressions": "NUMERIC",
        "clicks": "NUMERIC",
        "unique_clicks": "NUMERIC",
        "unique_inline_link_clicks": "NUMERIC",
        # Keep list/dict metrics in JSONB to avoid column explosion
        "results": "JSONB",
        "results_indicator": "TEXT",
        "results_value": "TEXT",
        "unique_outbound_clicks": "JSONB",
        "outbound_clicks": "JSONB",
        "actions": "JSONB",
        "action_values": "JSONB",
        "video_avg_time_watched_actions": "JSONB",
        "video_p25_watched_actions": "JSONB",
        "video_p50_watched_actions": "JSONB",
        "video_play_actions": "JSONB",
        "video_30_sec_watched_actions": "JSONB",
        "video_p100_watched_actions": "JSONB",
        "video_p75_watched_actions": "JSONB",
        "video_p95_watched_actions": "JSONB",
    },
    "fact_meta_delivery_adset": {
        "adset_id": "TEXT",
        "date_start": "DATE",
        "date_stop": "DATE",
    },
    "fact_meta_delivery_campaign": {
        "campaign_id": "TEXT",
        "date_start": "DATE",
        "date_stop": "DATE",
    },
    "fact_meta_delivery_account": {
        "account_id": "TEXT",
        "date_start": "DATE",
        "date_stop": "DATE",
    },
    "meta_insights_raw": {
        "id": "BIGSERIAL PRIMARY KEY",
        "account_id": "TEXT",
        "level": "TEXT",
        "date_start": "DATE",
        "date_stop": "DATE",
        "breakdowns": "TEXT",
        "fetched_at": "TIMESTAMPTZ DEFAULT now()",
        "payload": "JSONB NOT NULL",
    },
    "meta_accounts_raw": {
        "id": "BIGSERIAL PRIMARY KEY",
        "account_id": "TEXT",
        "fetched_at": "TIMESTAMPTZ DEFAULT now()",
        "payload": "JSONB NOT NULL",
    },
    "meta_creatives_raw": {
        "id": "BIGSERIAL PRIMARY KEY",
        "creative_id": "TEXT",
        "account_id": "TEXT",
        "fetched_at": "TIMESTAMPTZ DEFAULT now()",
        "payload": "JSONB NOT NULL",
    },
    "meta_campaigns_raw": {
        "id": "BIGSERIAL PRIMARY KEY",
        "campaign_id": "TEXT",
        "account_id": "TEXT",
        "fetched_at": "TIMESTAMPTZ DEFAULT now()",
        "payload": "JSONB NOT NULL",
    },
    "meta_adsets_raw": {
        "id": "BIGSERIAL PRIMARY KEY",
        "adset_id": "TEXT",
        "account_id": "TEXT",
        "campaign_id": "TEXT",
        "fetched_at": "TIMESTAMPTZ DEFAULT now()",
        "payload": "JSONB NOT NULL",
    },
    "meta_ads_raw": {
        "id": "BIGSERIAL PRIMARY KEY",
        "ad_id": "TEXT",
        "account_id": "TEXT",
        "adset_id": "TEXT",
        "campaign_id": "TEXT",
        "fetched_at": "TIMESTAMPTZ DEFAULT now()",
        "payload": "JSONB NOT NULL",
    },
    "meta_ads_previews_raw": {
        "id": "BIGSERIAL PRIMARY KEY",
        "ad_id": "TEXT",
        "account_id": "TEXT",
        "fetched_at": "TIMESTAMPTZ DEFAULT now()",
        "payload": "JSONB NOT NULL",
    },
}
