TABLE_SCHEMAS = {
    "dim_meta_accounts": {
        "id": "TEXT PRIMARY KEY",
        "account_name": "TEXT",
        "account_status": "INTEGER",
        "currency": "TEXT",
        "timezone_id": "INTEGER",
        "amount_spent": "NUMERIC",
        "spend_cap": "NUMERIC",
        "balance": "NUMERIC",
        "business_name": "TEXT",
        "disable_reason": "INTEGER",
        "funding_source_display": "TEXT",
        "funding_source_id": "TEXT",
        "funding_source_type": "TEXT",
        "created_time": "TIMESTAMPTZ",
    },
    "dim_meta_account_registry": {
        "account_id": "TEXT PRIMARY KEY",
        "account_name": "TEXT",
        "account_status": "INTEGER",
        "profile_name": "TEXT",
        "include_in_etl": "BOOLEAN",
        "notes": "TEXT",
    },
    # Legacy dimensions kept for compatibility (not part of core runtime)
    "dim_meta_creatives": {
        "creative_id": "TEXT PRIMARY KEY",
        "account_id": "TEXT",
        "creative_name": "TEXT",
        "title": "TEXT",
        "body": "TEXT",
        "description": "TEXT",
        "call_to_action_type": "TEXT",
        "image_url": "TEXT",
        "thumbnail_url": "TEXT",
        "image_hash": "TEXT",
        "video_id": "TEXT",
        "object_url": "TEXT",
        "link_url": "TEXT",
        "display_url": "TEXT",
        "effective_object_story_id": "TEXT",
        "status": "TEXT",
    },
    "dim_meta_ads": {
        "ad_id": "TEXT PRIMARY KEY",
        "account_id": "TEXT",
        "ad_name": "TEXT",
        "adset_id": "TEXT",
        "campaign_id": "TEXT",
        "creative_id": "TEXT",
        "creative_name": "TEXT",
        "status": "TEXT",
        "effective_status": "TEXT",
        "configured_status": "TEXT",
        "created_time": "TIMESTAMPTZ",
        "updated_time": "TIMESTAMPTZ",
        "ad_review_feedback_global_non_functional_landing_page": "TEXT",
    },
    "dim_meta_campaigns": {
        "campaign_id": "TEXT PRIMARY KEY",
        "account_id": "TEXT",
        "campaign_name": "TEXT",
    },
    "dim_meta_adsets": {
        "adset_id": "TEXT PRIMARY KEY",
        "account_id": "TEXT",
        "campaign_id": "TEXT",
        "adset_name": "TEXT",
    },
    "etl_run_log": {
        "run_id": "TEXT PRIMARY KEY",
        "command": "TEXT NOT NULL",
        "profile": "TEXT",
        "status": "TEXT NOT NULL",
        "started_at": "TIMESTAMPTZ NOT NULL",
        "ended_at": "TIMESTAMPTZ",
        "duration_seconds": "NUMERIC",
        "rows_loaded": "BIGINT",
        "error_message": "TEXT",
        "host": "TEXT",
    },
    "etl_insights_checkpoint": {
        "profile": "TEXT NOT NULL",
        "level": "TEXT NOT NULL",
        "breakdowns_key": "TEXT NOT NULL",
        "since": "DATE NOT NULL",
        "until": "DATE NOT NULL",
        "rows_loaded": "BIGINT",
        "completed_at": "TIMESTAMPTZ NOT NULL",
    },
    "dim_goals": {
        "account_id": "TEXT NOT NULL",
        "month": "DATE NOT NULL",
        "goal_spend": "NUMERIC",
        "goal_purchase_value": "NUMERIC",
        "goal_roas": "NUMERIC",
        "goal_purchases": "NUMERIC",
        "goal_messages": "NUMERIC",
        "note": "TEXT",
    },
    "fact_meta_delivery_ad": {
        "ad_id": "TEXT NOT NULL",
        "date_start": "DATE NOT NULL",
        "date_stop": "DATE NOT NULL",
        "account_id": "TEXT",
        "account_name": "TEXT",
        "campaign_id": "TEXT",
        "campaign_name": "TEXT",
        "adset_id": "TEXT",
        "adset_name": "TEXT",
        "ad_name": "TEXT",
        "objective": "TEXT",
        "optimization_goal": "TEXT",
        "spend": "NUMERIC",
        "social_spend": "NUMERIC",
        "reach": "NUMERIC",
        "impressions": "NUMERIC",
        "clicks": "NUMERIC",
        "unique_clicks": "NUMERIC",
        "unique_inline_link_clicks": "NUMERIC",
        "results": "JSONB",
        "results_indicator": "TEXT",
        "results_value": "TEXT",
        "unique_outbound_clicks": "JSONB",
        "outbound_clicks": "JSONB",
        "actions": "JSONB",
        "action_values": "JSONB",
        "video_avg_time_watched_actions": "JSONB",
        "video_p25_watched_actions": "JSONB",
        "video_p50_watched_actions": "JSONB",
        "video_play_actions": "JSONB",
        "video_30_sec_watched_actions": "JSONB",
        "video_p100_watched_actions": "JSONB",
        "video_p75_watched_actions": "JSONB",
        "video_p95_watched_actions": "JSONB",
    },
}
